services:
  mongodb:
    container_name: mongodb-wichat_en1b
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/authservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: ./users/authservice
    develop:
      watch:
        - action: rebuild
          path: ./users/authservice/package.json
          target: /usr/src/authservice/package.json

        - action: sync+restart
          path: ./users/authservice
          target: /usr/src/authservice
          ignore:
            - node_modules
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/userservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: ./users/userservice
    develop:
      watch:
        - action: rebuild
          path: ./users/userservice/package.json
          target: /usr/src/userservice/package.json

        - action: sync+restart
          path: ./users/userservice
          target: /usr/src/userservice
          ignore:
            - node_modules
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  llmservice:
    container_name: llmservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/llmservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: 
      context: ./llmservice
    develop:
      watch:
        - action: rebuild
          path: ./llmservice/package.json
          target: /usr/src/llmservice/package.json

        - action: sync+restart
          path: ./llmservice
          target: /usr/src/llmservice
          ignore:
            - node_modules
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  questionservice:
    container_name: questionservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/questionservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: ./questionservice
    develop:
      watch:
        - action: rebuild
          path: ./questionservice/package.json
          target: /usr/src/questionservice/package.json

        - action: sync+restart
          path: ./questionservice
          target: /usr/src/questionservice
          ignore:
            - node_modules
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questiondb
    
  statisticservice:
    container_name: statisticservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/statisticservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: 
      context: ./statisticservice
    develop:
      watch:
        - action: rebuild
          path: ./statisticservice/package.json
          target: /usr/src/statisticservice/package.json

        - action: sync+restart
          path: ./statisticservice
          target: /usr/src/statisticservice
          ignore:
            - node_modules
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  gatewayservice:
    container_name: gatewayservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/gatewayservice:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: ./gatewayservice
    develop:
      watch:
        - action: rebuild
          path: ./gatewayservice/package.json
          target: /usr/src/gatewayservice/package.json

        - action: sync+restart
          path: ./gatewayservice
          target: /usr/src/gatewayservice
          ignore:
            - node_modules
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
      - questionservice
      - statisticservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      USER_SERVICE_URL: http://userservice:8001
      AUTH_SERVICE_URL: http://authservice:8002
      LLM_SERVICE_URL: http://llmservice:8003
      QUESTION_SERVICE_URL: http://questionservice:8004
      STATS_SERVICE_URL: http://statisticservice:8005

  webapp:
    container_name: webapp-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/webapp:159-deploy-the-application
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build:
      context: ./webapp
      args:
        - REACT_APP_API_ENDPOINT
    develop:
      watch:
        - action: rebuild
          path: ./webapp/package.json
          target: /app/package.json
          
        - action: sync
          path: ./webapp
          target: /app
          ignore:
            - node_modules
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_en1b
    profiles: ["dev"]
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_en1b
    profiles: ["dev"]
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus

volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge